description:
  DSK’s new 1.3 release comes with full support for versioned design systems and many other improvements.
  
authors:
  - christoph@atelierdisko.de
  - mariuswilms@mailbox.org
tags:
  - release